In [1]:
# import library
import pandas as pd
print("Library imported succesfully")

Library imported succesfully

In [2]:
df=pd.read_csv("student_performance.csv")

In [3]:
#rows and col in dataset
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [4]:
#check if changes are there
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [5]:
#rows and col
print("shape of the Data:",df.shape)
#0->rows
print("No of studnets:",df.shape[0])
#1->col
print("Number of Columns",df.shape[1])

shape of the Data: (30, 13)
No of studnets: 30
Number of Columns 13

In [6]:
#col names
print("Column in database")
print(df.columns.tolist())

Column in database
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [7]:
#row spec values
print("rows in database")
print(df.index.tolist())

rows in database
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [8]:
#Data types

df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [9]:
#statistical summary
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [10]:
#null values
print(df.isnull().sum())

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [11]:
print(df.isnull().sum().sum())

0

In [12]:
#print names
print("Student Names")
print(df['name'])

Student Names
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [13]:
#Department (unique)
print("Department in the dataset")
print(df['department'].unique())

Department in the dataset
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [14]:
cs_students=df[df['department']=='Computer Science']

In [15]:
display(cs_students)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [16]:
print(f"Number of students in Computer Science department: {cs_students.shape[0]}")

Number of students in Computer Science department: 13

In [17]:
high_attendance = df[df['attendance_percentage'] >= 90]
#count
print(f"Number of students with high attendance: {high_attendance.shape[0]}")

Number of students with high attendance: 11

In [18]:
## top student
df['total_score']=df['math_score']+df['english_score']+df['programming_score']+df['science_score']
top_student = df.loc[df['total_score'].idxmax()]
print(top_student['name'])

Ananya Das

In [19]:
dept_avg = df.groupby('department')['total_score'].mean()
print("Average score for each department:")
print(dept_avg)

Average score for each department:
department
Civil               235.800000
Computer Science    340.153846
Electronics         277.500000
Mechanical          267.333333
Name: total_score, dtype: float64

In [20]:
df_sorted=df.sort_values(by='total_score',ascending=False)
top_students=df_sorted.head(10)
print("Top 5 students based on total score:")
print(top_students['name'])

Top 5 students based on total score:
9         Ananya Das
21       Tanvi Mehta
29    Akanksha Yadav
4         Arjun Nair
7        Divya Singh
17    Swati Kulkarni
24         Amit Bose
12        Suresh Rao
19      Nisha Kapoor
0       Aarav Sharma
Name: name, dtype: object

# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings

### Task 1: Display Project Title

In [33]:
print("="*50)
print("MINI PROJECT : Student Data Explorer")
print("="*50)

==================================================
MINI PROJECT : Student Data Explorer
==================================================

### Task 2: Dataset Overview

In [22]:
print(f"Total number of students: {df.shape[0]}")
print(f"Total number of columns: {df.shape[1]}")
print(f"Number of unique departments: {df['department'].nunique()}")

Total number of students: 30
Total number of columns: 14
Number of unique departments: 4

### Task 3: Department Wise Analysis

In [23]:
print("Count of students in each department:")
print(df['department'].value_counts())

Count of students in each department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

### Task 4: Score Analysis

In [24]:
print(f"Highest Math Score: {df['math_score'].max()}")
print(f"Lowest Math Score: {df['math_score'].min()}")
print(f"Average Math Score: {df['math_score'].mean():.2f}")
print(f"Average Programming Score: {df['programming_score'].mean():.2f}")
print(f"Average Attendance Percentage: {df['attendance_percentage'].mean():.2f}")

Highest Math Score: 95
Lowest Math Score: 56
Average Math Score: 76.07
Average Programming Score: 67.60
Average Attendance Percentage: 84.50

### Task 5: Gender Wise Analysis

In [25]:
print("Average total score by gender:")
print(df.groupby('gender')['total_score'].mean())

Average total score by gender:
gender
Female    310.666667
Male      280.666667
Name: total_score, dtype: float64

### Task 6: Top Performers (Top 5 Students)

In [26]:
top_5_students = df.sort_values(by='total_score', ascending=False).head(5)
print("Top 5 students based on total score:")
display(top_5_students[['name', 'department', 'total_score']])

Top 5 students based on total score:

              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

### Task 7: Attendance Analysis

In [27]:
low_attendance_students = df[df['attendance_percentage'] < 75]

if not low_attendance_students.empty:
    print("Students with attendance below 75%:")
    display(low_attendance_students[['name', 'department', 'attendance_percentage']])
else:
    print("All students have attendance above 75%.")

Students with attendance below 75%:

             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73

Practice Questions

Try solving these on your own. Answers are provided in the next section.

Question 1:

How many students are from the Electronics department?

Question 2:

What is the average attendance of female students?

Question 3:

Who is the student with the lowest programming score?

Question 4:

How many students scored above 80 in math?

Question 5:

What is the average total_score for students with attendance above 90%?

## Answers to Practice Questions

### Question 1: How many students are from the Electronics department?

In [28]:
electronics_students_count = df[df['department'] == 'Electronics'].shape[0]
print(f"Number of students from the Electronics department: {electronics_students_count}")

Number of students from the Electronics department: 6

### Question 2: What is the average attendance of female students?

In [29]:
avg_attendance_female = df[df['gender'] == 'Female']['attendance_percentage'].mean()
print(f"Average attendance of female students: {avg_attendance_female:.2f}%")

Average attendance of female students: 88.53%

### Question 3: Who is the student with the lowest programming score?

In [30]:
lowest_programming_student = df.loc[df['programming_score'].idxmin()]
print(f"Student with the lowest programming score: {lowest_programming_student['name']} (Score: {lowest_programming_student['programming_score']})")

Student with the lowest programming score: Manoj Pandey (Score: 38)

### Question 4: How many students scored above 80 in math?

In [31]:
students_above_80_math = df[df['math_score'] > 80].shape[0]
print(f"Number of students who scored above 80 in math: {students_above_80_math}")

Number of students who scored above 80 in math: 11

### Question 5: What is the average total_score for students with attendance above 90%?

In [32]:
avg_total_score_high_attendance = df[df['attendance_percentage'] > 90]['total_score'].mean()
print(f"Average total score for students with attendance above 90%: {avg_total_score_high_attendance:.2f}")

Average total score for students with attendance above 90%: 335.80